# .go-mutesting.yml
# Official mutation testing configuration for tf-analyzer
# This configuration ensures test suite quality and follows strategic testing framework

test:
  command: "go test -v -run=."
  timeout: "30s"

mutators:
  # Swap binary operators (+ to -, * to /, == to !=, etc.)
  - name: "binary-operator"
    enabled: true

  # Change conditional boundaries (< to <=, > to >=, etc.)
  - name: "conditional-boundaries"
    enabled: true

  # Negate conditionals (if a == b -> if a != b)
  - name: "conditional-negation"
    enabled: true

  # Remove a statement entirely
  - name: "statement-removal"
    enabled: true

  # Replace constants with different values
  - name: "constant-replacement"
    enabled: true

  # Invert boolean expressions
  - name: "boolean-inversion"
    enabled: true

# Exclude files that don't need mutation testing
exclude:
  - "*_test.go"
  - "*.pb.go"
  - "*_gen.go"
  - "vendor/*"
  - ".git/*"

# Minimum mutation score target (85% as per framework requirements)
threshold: 95

# Fail build if mutation score is below target
fail_on_low_score: true

